### ISSUE TITLE
Error sending campaign

### ISSUE THREAD

**Issue by davidgalarza** [parcelvoy/platform#365]
I deployed the system using a digital ocean droplet and docker and when I'm trying to launch a campaign, the campaign is never staring
<img width="1156" alt="Screenshot 2024-02-29 at 11 07 53 PM" src="https://github.com/parcelvoy/platform/assets/20847597/e282db59-ea54-480f-96c6-4314b2807f6a">
Here is the error log
```
[1709265841097] ERROR (7 on 2aaf90a05584): queue:job:errored
    stacktrace: "Error: select * from `lists` where `id` in ({\"id\":2,\"created_at\":\"2024-03-01T03:57:27.000Z\",\"updated_at\":\"2024-03-01T04:00:00.000Z\",\"project_id\":1,\"name\":\"galad\",\"type\":\"dynamic\",\"state\":\"ready\",\"rule_id\":1,\"rule\":null,\"version\":4,\"users_count\":2,\"tags\":[\"users\"],\"is_visible\":true,\"deleted_at\":null}) - Unknown column 'tags' in 'where clause'\n    at createQueryBuilder (/usr/src/app/node_modules/knex/lib/knex-builder/make-knex.js:320:26)\n    at knex (/usr/src/app/node_modules/knex/lib/knex-builder/make-knex.js:101:12)\n    at List.table (/usr/src/app/build/core/Model.js:244:16)\n    at List.query (/usr/src/app/build/core/Model.js:59:21)\n    at estimatedSendSize (/usr/src/app/build/campaigns/CampaignService.js:383:40)\n    at handler (/usr/src/app/build/campaigns/CampaignGenerateListJob.js:21:77)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Queue.dequeue (/usr/src/app/build/queue/Queue.js:59:9)\n    at async worker.bullmq_1.Worker.connection [as processFn] (/usr/src/app/build/queue/RedisQueueProvider.js:78:13)\n    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:389:28)\n    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:578:24)"
    job: {
      "name": "campaign_generate_list_job",
      "data": {
        "id": 2,
        "type": "blast",
        "project_id": 1,
        "list_ids": [
          2
        ],
        "exclusion_list_ids": null,
        "name": "Prueba",
        "channel": "email",
        "provider_id": 1,
        "subscription_id": 1,
        "state": "pending",
        "delivery": {
          "sent": 0,
          "opens": 0,
          "total": 2,
          "clicks": 0
        },
        "send_at": "2024-03-01T04:01:58.000Z",
        "send_in_user_timezone": false,
        "created_at": "2024-03-01T03:59:30.000Z",
        "updated_at": "2024-03-01T04:01:59.000Z",
        "deleted_at": null
      },
      "options": {
        "delay": 0,
        "attempts": 3
      }
    }
    error: {
      "code": "ER_BAD_FIELD_ERROR",
      "errno": 1054,
      "sqlState": "42S22",
      "sqlMessage": "Unknown column 'tags' in 'where clause'",
      "sql": "select * from `lists` where `id` in (`id` = 2, `created_at` = '2024-03-01 03:57:27.000', `updated_at` = '2024-03-01 04:00:00.000', `project_id` = 1, `name` = 'galad', `type` = 'dynamic', `state` = 'ready', `rule_id` = 1, `rule` = NULL, `version` = 4, `users_count` = 2, `tags` = 'users', `is_visible` = true, `deleted_at` = NULL)",
      "originalStack": "Error: select * from `lists` where `id` in ({\"id\":2,\"created_at\":\"2024-03-01T03:57:27.000Z\",\"updated_at\":\"2024-03-01T04:00:00.000Z\",\"project_id\":1,\"name\":\"galad\",\"type\":\"dynamic\",\"state\":\"ready\",\"rule_id\":1,\"rule\":null,\"version\":4,\"users_count\":2,\"tags\":[\"users\"],\"is_visible\":true,\"deleted_at\":null}) - Unknown column 'tags' in 'where clause'\n    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)\n    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32)\n    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12)\n    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
    }
```

**Comment by pushchris** [comment]
Thanks for reporting this! A fix is available in v1.3.1 please let us know if you run into any other issues!
