### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by mjp0** [parcelvoy/platform#590]
I'm trying to send a proof email, and I see this in the logs. Any idea what's causing it?
```
api-1     |   TypeError: Converting circular structure to JSON
api-1     |       --> starting at object with constructor 'Mail'
api-1     |       |     property 'transporter' -> object with constructor 'SMTPTransport'
api-1     |       --- property 'mailer' closes the circle
api-1     |       at JSON.stringify (<anonymous>)
api-1     |       at respond (/usr/src/app/node_modules/koa/lib/application.js:306:15)
api-1     |       at handleResponse (/usr/src/app/node_modules/koa/lib/application.js:184:34)
api-1     |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by mjp0** [comment]
Not sure what was going on here. I changed the SMTP port number and the problem fixed itself 🤷‍♂️
